// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoNum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from ProtoNum.proto</summary>
  public static partial class ProtoNumReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoNum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoNumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b051bS5wcm90bxIHbWVzc2FnZSrGBQoIUHJvdG9OdW0SCwoHVW5r",
            "bm93bhAAEhMKDkNNTG9naW5SZXF1ZXN0EOkHEhEKDENNTG9naW5SZXBseRDq",
            "BxITCg5DTU1hdGNoUmVxdWVzdBDrBxIRCgxDTU1hdGNoUmVwbHkQ7AcSEwoO",
            "Q01NYXRjaFN1Y2Nlc3MQ7gcSEgoNQ01NYXRjaENhbmNlbBDvBxIWChFDTUNh",
            "bmNlbFJlY29ubmVjdBDxBxIVChBDTVBsYXllckluZm9TeW5jEPQHEhMKDkNC",
            "TG9naW5SZXF1ZXN0ENEPEhEKDENCTG9naW5SZXBseRDSDxIYChNDQkpvaW5C",
            "YXR0bGVSZXF1ZXN0ENMPEhYKEUNCSm9pbkJhdHRsZVJlcGx5ENQPEgwKB0NC",
            "UmVhZHkQ1Q8SEAoLQ0JSZWFkeVN5bmMQ1g8SDwoKQ0JSb29tU3luYxDYDxIT",
            "Cg5DQkNhcmRJbmZvU3luYxDaDxIPCgpDQlBsYXlDYXJkENsPEhMKDkNCUGxh",
            "eUNhcmRTeW5jENwPEhMKDkNCU2VuZENhcmRTeW5jEN4PEhcKEkNCQmF0dGxl",
            "UmVzdWx0U3luYxDgDxIVChBDQkNhcmRFZmZlY3RTeW5jEOIPEhkKFENCUGxh",
            "eWVyRHJvcENhcmRTeW5jEOQPEhQKD0NCUGxheWVyT3V0U3luYxDmDxISCg1D",
            "QlNlbmRNZXNzYWdlEOcPEhYKEUNCU2VuZE1lc3NhZ2VTeW5jEOgPEhcKEkNC",
            "UmVjb25uZWN0UmVxdWVzdBDpDxIVChBDQlJlY29ubmVjdFJlcGx5EOoPEhMK",
            "DkJNTG9naW5SZXF1ZXN0ELkXEhEKDEJNTG9naW5SZXBseRC6FxIYChNCTUNy",
            "ZWF0ZVJvb21SZXF1ZXN0ELsXEhYKEUJNQ3JlYXRlUm9vbVJlcGx5ELwXEhMK",
            "DkJNQmF0dGxlUmVzdWx0EL0XYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.ProtoNum), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 消息头枚举，不用于消息收发
  /// !!! 名字必须对应到消息类型
  /// </summary>
  public enum ProtoNum {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    /// <summary>
    ///Client -> Main
    /// </summary>
    [pbr::OriginalName("CMLoginRequest")] CmloginRequest = 1001,
    [pbr::OriginalName("CMLoginReply")] CmloginReply = 1002,
    [pbr::OriginalName("CMMatchRequest")] CmmatchRequest = 1003,
    [pbr::OriginalName("CMMatchReply")] CmmatchReply = 1004,
    [pbr::OriginalName("CMMatchSuccess")] CmmatchSuccess = 1006,
    [pbr::OriginalName("CMMatchCancel")] CmmatchCancel = 1007,
    [pbr::OriginalName("CMCancelReconnect")] CmcancelReconnect = 1009,
    [pbr::OriginalName("CMPlayerInfoSync")] CmplayerInfoSync = 1012,
    /// <summary>
    ///Client -> Battle
    /// </summary>
    [pbr::OriginalName("CBLoginRequest")] CbloginRequest = 2001,
    [pbr::OriginalName("CBLoginReply")] CbloginReply = 2002,
    [pbr::OriginalName("CBJoinBattleRequest")] CbjoinBattleRequest = 2003,
    [pbr::OriginalName("CBJoinBattleReply")] CbjoinBattleReply = 2004,
    [pbr::OriginalName("CBReady")] Cbready = 2005,
    [pbr::OriginalName("CBReadySync")] CbreadySync = 2006,
    [pbr::OriginalName("CBRoomSync")] CbroomSync = 2008,
    [pbr::OriginalName("CBCardInfoSync")] CbcardInfoSync = 2010,
    [pbr::OriginalName("CBPlayCard")] CbplayCard = 2011,
    [pbr::OriginalName("CBPlayCardSync")] CbplayCardSync = 2012,
    [pbr::OriginalName("CBSendCardSync")] CbsendCardSync = 2014,
    [pbr::OriginalName("CBBattleResultSync")] CbbattleResultSync = 2016,
    [pbr::OriginalName("CBCardEffectSync")] CbcardEffectSync = 2018,
    [pbr::OriginalName("CBPlayerDropCardSync")] CbplayerDropCardSync = 2020,
    [pbr::OriginalName("CBPlayerOutSync")] CbplayerOutSync = 2022,
    [pbr::OriginalName("CBSendMessage")] CbsendMessage = 2023,
    [pbr::OriginalName("CBSendMessageSync")] CbsendMessageSync = 2024,
    [pbr::OriginalName("CBReconnectRequest")] CbreconnectRequest = 2025,
    [pbr::OriginalName("CBReconnectReply")] CbreconnectReply = 2026,
    /// <summary>
    ///Battle -> Main
    /// </summary>
    [pbr::OriginalName("BMLoginRequest")] BmloginRequest = 3001,
    [pbr::OriginalName("BMLoginReply")] BmloginReply = 3002,
    [pbr::OriginalName("BMCreateRoomRequest")] BmcreateRoomRequest = 3003,
    [pbr::OriginalName("BMCreateRoomReply")] BmcreateRoomReply = 3004,
    [pbr::OriginalName("BMBattleResult")] BmbattleResult = 3005,
  }

  #endregion

}

#endregion Designer generated code
