// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMMatchSuccess.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from CMMatchSuccess.proto</summary>
  public static partial class CMMatchSuccessReflection {

    #region Descriptor
    /// <summary>File descriptor for CMMatchSuccess.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CMMatchSuccessReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDTU1hdGNoU3VjY2Vzcy5wcm90bxIHbWVzc2FnZRoLSW5mb3MucHJvdG8i",
            "RQoOQ01NYXRjaFN1Y2Nlc3MSMwoQYmF0dGxlU2VydmVySW5mbxgBIAEoCzIZ",
            "Lm1lc3NhZ2UuQmF0dGxlU2VydmVySW5mb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.InfosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.CMMatchSuccess), global::Message.CMMatchSuccess.Parser, new[]{ "BattleServerInfo" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 主服 -> 客户端 匹配成功响应
  /// </summary>
  public sealed partial class CMMatchSuccess : pb::IMessage<CMMatchSuccess> {
    private static readonly pb::MessageParser<CMMatchSuccess> _parser = new pb::MessageParser<CMMatchSuccess>(() => new CMMatchSuccess());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CMMatchSuccess> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.CMMatchSuccessReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMMatchSuccess() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMMatchSuccess(CMMatchSuccess other) : this() {
      BattleServerInfo = other.battleServerInfo_ != null ? other.BattleServerInfo.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMMatchSuccess Clone() {
      return new CMMatchSuccess(this);
    }

    /// <summary>Field number for the "battleServerInfo" field.</summary>
    public const int BattleServerInfoFieldNumber = 1;
    private global::Message.BattleServerInfo battleServerInfo_;
    /// <summary>
    ///战场信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.BattleServerInfo BattleServerInfo {
      get { return battleServerInfo_; }
      set {
        battleServerInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CMMatchSuccess);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CMMatchSuccess other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BattleServerInfo, other.BattleServerInfo)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (battleServerInfo_ != null) hash ^= BattleServerInfo.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (battleServerInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BattleServerInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (battleServerInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleServerInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CMMatchSuccess other) {
      if (other == null) {
        return;
      }
      if (other.battleServerInfo_ != null) {
        if (battleServerInfo_ == null) {
          battleServerInfo_ = new global::Message.BattleServerInfo();
        }
        BattleServerInfo.MergeFrom(other.BattleServerInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (battleServerInfo_ == null) {
              battleServerInfo_ = new global::Message.BattleServerInfo();
            }
            input.ReadMessage(battleServerInfo_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
