// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMStartGameReply.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from CMStartGameReply.proto</summary>
  public static partial class CMStartGameReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for CMStartGameReply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CMStartGameReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZDTVN0YXJ0R2FtZVJlcGx5LnByb3RvEgdtZXNzYWdlGgtJbmZvcy5wcm90",
            "byJWChBDTVN0YXJ0R2FtZVJlcGx5Ei8KDGJhdHRsZVNlcnZlchgBIAEoCzIZ",
            "Lm1lc3NhZ2UuQmF0dGxlU2VydmVySW5mbxIRCglzZXNzaW9uSUQYAiABKAli",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.InfosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.CMStartGameReply), global::Message.CMStartGameReply.Parser, new[]{ "BattleServer", "SessionID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 主服 -> 客户端 开始游戏响应
  /// </summary>
  public sealed partial class CMStartGameReply : pb::IMessage<CMStartGameReply> {
    private static readonly pb::MessageParser<CMStartGameReply> _parser = new pb::MessageParser<CMStartGameReply>(() => new CMStartGameReply());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CMStartGameReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.CMStartGameReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMStartGameReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMStartGameReply(CMStartGameReply other) : this() {
      BattleServer = other.battleServer_ != null ? other.BattleServer.Clone() : null;
      sessionID_ = other.sessionID_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CMStartGameReply Clone() {
      return new CMStartGameReply(this);
    }

    /// <summary>Field number for the "battleServer" field.</summary>
    public const int BattleServerFieldNumber = 1;
    private global::Message.BattleServerInfo battleServer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.BattleServerInfo BattleServer {
      get { return battleServer_; }
      set {
        battleServer_ = value;
      }
    }

    /// <summary>Field number for the "sessionID" field.</summary>
    public const int SessionIDFieldNumber = 2;
    private string sessionID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SessionID {
      get { return sessionID_; }
      set {
        sessionID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CMStartGameReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CMStartGameReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BattleServer, other.BattleServer)) return false;
      if (SessionID != other.SessionID) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (battleServer_ != null) hash ^= BattleServer.GetHashCode();
      if (SessionID.Length != 0) hash ^= SessionID.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (battleServer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BattleServer);
      }
      if (SessionID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (battleServer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleServer);
      }
      if (SessionID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CMStartGameReply other) {
      if (other == null) {
        return;
      }
      if (other.battleServer_ != null) {
        if (battleServer_ == null) {
          battleServer_ = new global::Message.BattleServerInfo();
        }
        BattleServer.MergeFrom(other.BattleServer);
      }
      if (other.SessionID.Length != 0) {
        SessionID = other.SessionID;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (battleServer_ == null) {
              battleServer_ = new global::Message.BattleServerInfo();
            }
            input.ReadMessage(battleServer_);
            break;
          }
          case 18: {
            SessionID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
