//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Enums.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Enums")]
  public partial class Enums : global::ProtoBuf.IExtensible
  {
    public Enums() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ChessType")]
    public enum ChessType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=1)]
      None = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"White", Value=2)]
      White = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Black", Value=3)]
      Black = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Camp")]
    public enum Camp
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoneCamp", Value=1)]
      NoneCamp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WhiteCamp", Value=2)]
      WhiteCamp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlackCamp", Value=3)]
      BlackCamp = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
