//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlaceStatisticsSync.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChessPlaceStatistics")]
  public partial class ChessPlaceStatistics : global::ProtoBuf.IExtensible
  {
    public ChessPlaceStatistics() {}
    
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private float _ratio = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ratio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ratio
    {
      get { return _ratio; }
      set { _ratio = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaceStatisticsSync")]
  public partial class PlaceStatisticsSync : global::ProtoBuf.IExtensible
  {
    public PlaceStatisticsSync() {}
    
    private readonly global::System.Collections.Generic.List<message.ChessPlaceStatistics> _statistics = new global::System.Collections.Generic.List<message.ChessPlaceStatistics>();
    [global::ProtoBuf.ProtoMember(1, Name=@"statistics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<message.ChessPlaceStatistics> statistics
    {
      get { return _statistics; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
