// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CBSendCardSync.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from CBSendCardSync.proto</summary>
  public static partial class CBSendCardSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for CBSendCardSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CBSendCardSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDQlNlbmRDYXJkU3luYy5wcm90bxIHbWVzc2FnZSIyCg5DQlNlbmRDYXJk",
            "U3luYxIQCgh0YXJnZXRJRBgBIAEoBRIOCgZjYXJkSUQYAiABKAViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.CBSendCardSync), global::Message.CBSendCardSync.Parser, new[]{ "TargetID", "CardID" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CBSendCardSync : pb::IMessage<CBSendCardSync> {
    private static readonly pb::MessageParser<CBSendCardSync> _parser = new pb::MessageParser<CBSendCardSync>(() => new CBSendCardSync());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CBSendCardSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.CBSendCardSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBSendCardSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBSendCardSync(CBSendCardSync other) : this() {
      targetID_ = other.targetID_;
      cardID_ = other.cardID_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBSendCardSync Clone() {
      return new CBSendCardSync(this);
    }

    /// <summary>Field number for the "targetID" field.</summary>
    public const int TargetIDFieldNumber = 1;
    private int targetID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetID {
      get { return targetID_; }
      set {
        targetID_ = value;
      }
    }

    /// <summary>Field number for the "cardID" field.</summary>
    public const int CardIDFieldNumber = 2;
    private int cardID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CardID {
      get { return cardID_; }
      set {
        cardID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CBSendCardSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CBSendCardSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetID != other.TargetID) return false;
      if (CardID != other.CardID) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetID != 0) hash ^= TargetID.GetHashCode();
      if (CardID != 0) hash ^= CardID.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TargetID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TargetID);
      }
      if (CardID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CardID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TargetID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetID);
      }
      if (CardID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CardID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CBSendCardSync other) {
      if (other == null) {
        return;
      }
      if (other.TargetID != 0) {
        TargetID = other.TargetID;
      }
      if (other.CardID != 0) {
        CardID = other.CardID;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TargetID = input.ReadInt32();
            break;
          }
          case 16: {
            CardID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
