// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protonum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from protonum.proto</summary>
  public static partial class ProtonumReflection {

    #region Descriptor
    /// <summary>File descriptor for protonum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtonumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b251bS5wcm90bxIHbWVzc2FnZSq+BAoIUHJvdG9OdW0SCwoHVW5r",
            "bm93bhAAEhMKDkNNTG9naW5SZXF1ZXN0EOkHEhEKDENNTG9naW5SZXBseRDq",
            "BxITCg5DTU1hdGNoUmVxdWVzdBDrBxIRCgxDTU1hdGNoUmVwbHkQ7AcSEwoO",
            "Q01NYXRjaFN1Y2Nlc3MQ7gcSEgoNQ01NYXRjaENhbmNlbBDvBxIWChFDTUNh",
            "bmNlbFJlY29ubmVjdBDxBxITCg5DQkxvZ2luUmVxdWVzdBDRDxIRCgxDQkxv",
            "Z2luUmVwbHkQ0g8SGAoTQ0JKb2luQmF0dGxlUmVxdWVzdBDTDxIWChFDQkpv",
            "aW5CYXR0bGVSZXBseRDUDxIMCgdDQlJlYWR5ENUPEhAKC0NCUmVhZHlTeW5j",
            "ENYPEg8KCkNCUm9vbVN5bmMQ2A8SEwoOQ0JDYXJkSW5mb1N5bmMQ2g8SDwoK",
            "Q0JQbGF5Q2FyZBDbDxITCg5DQlBsYXlDYXJkU3luYxDcDxITCg5DQlNlbmRD",
            "YXJkU3luYxDeDxIXChJDQkJhdHRsZVJlc3VsdFN5bmMQ4A8SFQoQQ0JDYXJk",
            "RWZmZWN0U3luYxDiDxIZChRDQlBsYXllckRyb3BDYXJkU3luYxDkDxIUCg9D",
            "QlBsYXllck91dFN5bmMQ5g8SEwoOQk1Mb2dpblJlcXVlc3QQuRcSEQoMQk1M",
            "b2dpblJlcGx5ELoXEhgKE0JNQ3JlYXRlUm9vbVJlcXVlc3QQuxcSFgoRQk1D",
            "cmVhdGVSb29tUmVwbHkQvBdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.ProtoNum), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 消息头枚举，不用于消息收发
  /// !!! 名字必须对应到消息类型
  /// </summary>
  public enum ProtoNum {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    /// <summary>
    ///Client -> Main
    /// </summary>
    [pbr::OriginalName("CMLoginRequest")] CmloginRequest = 1001,
    [pbr::OriginalName("CMLoginReply")] CmloginReply = 1002,
    [pbr::OriginalName("CMMatchRequest")] CmmatchRequest = 1003,
    [pbr::OriginalName("CMMatchReply")] CmmatchReply = 1004,
    [pbr::OriginalName("CMMatchSuccess")] CmmatchSuccess = 1006,
    [pbr::OriginalName("CMMatchCancel")] CmmatchCancel = 1007,
    [pbr::OriginalName("CMCancelReconnect")] CmcancelReconnect = 1009,
    /// <summary>
    ///Client -> Battle
    /// </summary>
    [pbr::OriginalName("CBLoginRequest")] CbloginRequest = 2001,
    [pbr::OriginalName("CBLoginReply")] CbloginReply = 2002,
    [pbr::OriginalName("CBJoinBattleRequest")] CbjoinBattleRequest = 2003,
    [pbr::OriginalName("CBJoinBattleReply")] CbjoinBattleReply = 2004,
    [pbr::OriginalName("CBReady")] Cbready = 2005,
    [pbr::OriginalName("CBReadySync")] CbreadySync = 2006,
    [pbr::OriginalName("CBRoomSync")] CbroomSync = 2008,
    [pbr::OriginalName("CBCardInfoSync")] CbcardInfoSync = 2010,
    [pbr::OriginalName("CBPlayCard")] CbplayCard = 2011,
    [pbr::OriginalName("CBPlayCardSync")] CbplayCardSync = 2012,
    [pbr::OriginalName("CBSendCardSync")] CbsendCardSync = 2014,
    [pbr::OriginalName("CBBattleResultSync")] CbbattleResultSync = 2016,
    [pbr::OriginalName("CBCardEffectSync")] CbcardEffectSync = 2018,
    [pbr::OriginalName("CBPlayerDropCardSync")] CbplayerDropCardSync = 2020,
    [pbr::OriginalName("CBPlayerOutSync")] CbplayerOutSync = 2022,
    /// <summary>
    ///Battle -> Main
    /// </summary>
    [pbr::OriginalName("BMLoginRequest")] BmloginRequest = 3001,
    [pbr::OriginalName("BMLoginReply")] BmloginReply = 3002,
    [pbr::OriginalName("BMCreateRoomRequest")] BmcreateRoomRequest = 3003,
    [pbr::OriginalName("BMCreateRoomReply")] BmcreateRoomReply = 3004,
  }

  #endregion

}

#endregion Designer generated code
