// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BMLoginRequest.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from BMLoginRequest.proto</summary>
  public static partial class BMLoginRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for BMLoginRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BMLoginRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRCTUxvZ2luUmVxdWVzdC5wcm90bxIHbWVzc2FnZSIpCg5CTUxvZ2luUmVx",
            "dWVzdBIXCg9saXN0ZW5lckFkZHJlc3MYASABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.BMLoginRequest), global::Message.BMLoginRequest.Parser, new[]{ "ListenerAddress" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 战场 -> 主服 登录请求
  /// </summary>
  public sealed partial class BMLoginRequest : pb::IMessage<BMLoginRequest> {
    private static readonly pb::MessageParser<BMLoginRequest> _parser = new pb::MessageParser<BMLoginRequest>(() => new BMLoginRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BMLoginRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.BMLoginRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BMLoginRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BMLoginRequest(BMLoginRequest other) : this() {
      listenerAddress_ = other.listenerAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BMLoginRequest Clone() {
      return new BMLoginRequest(this);
    }

    /// <summary>Field number for the "listenerAddress" field.</summary>
    public const int ListenerAddressFieldNumber = 1;
    private string listenerAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ListenerAddress {
      get { return listenerAddress_; }
      set {
        listenerAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BMLoginRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BMLoginRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ListenerAddress != other.ListenerAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ListenerAddress.Length != 0) hash ^= ListenerAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ListenerAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ListenerAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ListenerAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ListenerAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BMLoginRequest other) {
      if (other == null) {
        return;
      }
      if (other.ListenerAddress.Length != 0) {
        ListenerAddress = other.ListenerAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ListenerAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
