// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CBBattleResultSync.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from CBBattleResultSync.proto</summary>
  public static partial class CBBattleResultSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for CBBattleResultSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CBBattleResultSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDQkJhdHRsZVJlc3VsdFN5bmMucHJvdG8SB21lc3NhZ2UaC0luZm9zLnBy",
            "b3RvIkoKEkNCQmF0dGxlUmVzdWx0U3luYxI0CgtyZXN1bHRJbmZvcxgBIAMo",
            "CzIfLm1lc3NhZ2UuQmF0dGxlUmVzdWx0UGxheWVySW5mb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.InfosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.CBBattleResultSync), global::Message.CBBattleResultSync.Parser, new[]{ "ResultInfos" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CBBattleResultSync : pb::IMessage<CBBattleResultSync> {
    private static readonly pb::MessageParser<CBBattleResultSync> _parser = new pb::MessageParser<CBBattleResultSync>(() => new CBBattleResultSync());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CBBattleResultSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.CBBattleResultSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBBattleResultSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBBattleResultSync(CBBattleResultSync other) : this() {
      resultInfos_ = other.resultInfos_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBBattleResultSync Clone() {
      return new CBBattleResultSync(this);
    }

    /// <summary>Field number for the "resultInfos" field.</summary>
    public const int ResultInfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Message.BattleResultPlayerInfo> _repeated_resultInfos_codec
        = pb::FieldCodec.ForMessage(10, global::Message.BattleResultPlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::Message.BattleResultPlayerInfo> resultInfos_ = new pbc::RepeatedField<global::Message.BattleResultPlayerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.BattleResultPlayerInfo> ResultInfos {
      get { return resultInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CBBattleResultSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CBBattleResultSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resultInfos_.Equals(other.resultInfos_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resultInfos_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      resultInfos_.WriteTo(output, _repeated_resultInfos_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += resultInfos_.CalculateSize(_repeated_resultInfos_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CBBattleResultSync other) {
      if (other == null) {
        return;
      }
      resultInfos_.Add(other.resultInfos_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            resultInfos_.AddEntriesFrom(input, _repeated_resultInfos_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
