// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CBPlayCardSync.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from CBPlayCardSync.proto</summary>
  public static partial class CBPlayCardSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for CBPlayCardSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CBPlayCardSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDQlBsYXlDYXJkU3luYy5wcm90bxIHbWVzc2FnZSJSCg5DQlBsYXlDYXJk",
            "U3luYxIOCgZmcm9tSUQYASABKAUSEAoIdGFyZ2V0SUQYAiABKAUSDgoGY2Fy",
            "ZElEGAMgASgFEg4KBmV4dGVuZBgEIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.CBPlayCardSync), global::Message.CBPlayCardSync.Parser, new[]{ "FromID", "TargetID", "CardID", "Extend" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CBPlayCardSync : pb::IMessage<CBPlayCardSync> {
    private static readonly pb::MessageParser<CBPlayCardSync> _parser = new pb::MessageParser<CBPlayCardSync>(() => new CBPlayCardSync());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CBPlayCardSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.CBPlayCardSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBPlayCardSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBPlayCardSync(CBPlayCardSync other) : this() {
      fromID_ = other.fromID_;
      targetID_ = other.targetID_;
      cardID_ = other.cardID_;
      extend_ = other.extend_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CBPlayCardSync Clone() {
      return new CBPlayCardSync(this);
    }

    /// <summary>Field number for the "fromID" field.</summary>
    public const int FromIDFieldNumber = 1;
    private int fromID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FromID {
      get { return fromID_; }
      set {
        fromID_ = value;
      }
    }

    /// <summary>Field number for the "targetID" field.</summary>
    public const int TargetIDFieldNumber = 2;
    private int targetID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetID {
      get { return targetID_; }
      set {
        targetID_ = value;
      }
    }

    /// <summary>Field number for the "cardID" field.</summary>
    public const int CardIDFieldNumber = 3;
    private int cardID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CardID {
      get { return cardID_; }
      set {
        cardID_ = value;
      }
    }

    /// <summary>Field number for the "extend" field.</summary>
    public const int ExtendFieldNumber = 4;
    private int extend_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Extend {
      get { return extend_; }
      set {
        extend_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CBPlayCardSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CBPlayCardSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromID != other.FromID) return false;
      if (TargetID != other.TargetID) return false;
      if (CardID != other.CardID) return false;
      if (Extend != other.Extend) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FromID != 0) hash ^= FromID.GetHashCode();
      if (TargetID != 0) hash ^= TargetID.GetHashCode();
      if (CardID != 0) hash ^= CardID.GetHashCode();
      if (Extend != 0) hash ^= Extend.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FromID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FromID);
      }
      if (TargetID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetID);
      }
      if (CardID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CardID);
      }
      if (Extend != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Extend);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FromID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromID);
      }
      if (TargetID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetID);
      }
      if (CardID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CardID);
      }
      if (Extend != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Extend);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CBPlayCardSync other) {
      if (other == null) {
        return;
      }
      if (other.FromID != 0) {
        FromID = other.FromID;
      }
      if (other.TargetID != 0) {
        TargetID = other.TargetID;
      }
      if (other.CardID != 0) {
        CardID = other.CardID;
      }
      if (other.Extend != 0) {
        Extend = other.Extend;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            FromID = input.ReadInt32();
            break;
          }
          case 16: {
            TargetID = input.ReadInt32();
            break;
          }
          case 24: {
            CardID = input.ReadInt32();
            break;
          }
          case 32: {
            Extend = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
