//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlaceRequest.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaceRequest")]
  public partial class PlaceRequest : global::ProtoBuf.IExtensible
  {
    public PlaceRequest() {}
    
    private int _chessNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chessNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chessNum
    {
      get { return _chessNum; }
      set { _chessNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
